-- Run this script in the Supabase SQL Editor

CREATE TABLE pamphlets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zone TEXT NOT NULL,
  image_url TEXT NOT NULL,
  file_name TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

ALTER TABLE pamphlets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users on pamphlets" ON pamphlets FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only on pamphlets" ON pamphlets FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update for authenticated users only on pamphlets" ON pamphlets FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Enable delete for authenticated users only on pamphlets" ON pamphlets FOR DELETE USING (auth.role() = 'authenticated');

-- IMPORTANT: You must also create a storage bucket named "pamphlets" and set it to Public.
