-- =============================================================================
-- Phase 9 — Home page image slideshow (global banners managed by admin).
-- Run this in the Supabase SQL Editor.
--
-- One global, ordered set of banner images shown in the home-page slideshow.
-- Images are stored in the existing "pamphlets" storage bucket under a
-- "slideshow/" folder, so the phase 8 storage policies already cover uploads.
-- =============================================================================

CREATE TABLE IF NOT EXISTS slideshow_images (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_url  TEXT NOT NULL,
  file_name  TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_slideshow_sort ON slideshow_images(sort_order);

ALTER TABLE slideshow_images ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read slideshow" ON slideshow_images;
DROP POLICY IF EXISTS "Authenticated insert slideshow" ON slideshow_images;
DROP POLICY IF EXISTS "Authenticated update slideshow" ON slideshow_images;
DROP POLICY IF EXISTS "Authenticated delete slideshow" ON slideshow_images;

CREATE POLICY "Public read slideshow"
  ON slideshow_images FOR SELECT USING (true);
CREATE POLICY "Authenticated insert slideshow"
  ON slideshow_images FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated update slideshow"
  ON slideshow_images FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated delete slideshow"
  ON slideshow_images FOR DELETE USING (auth.role() = 'authenticated');
