-- =============================================================================
-- Phase 11 — Blog posts (articles managed by admin, shown on the home page
-- carousel and at /blog).
-- Run this in the Supabase SQL Editor (or applied via the Supabase MCP).
--
-- Cover images are stored in the existing "pamphlets" storage bucket under a
-- "blog/" folder, so the phase 8 storage policies already cover uploads.
-- =============================================================================

CREATE TABLE IF NOT EXISTS blog_posts (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug       TEXT NOT NULL UNIQUE,
  title      TEXT NOT NULL,
  excerpt    TEXT,                              -- card subtitle / listing summary
  body       TEXT,                              -- full article (HTML)
  cover_url  TEXT,                              -- cover image (pamphlets bucket, blog/ folder)
  published  BOOLEAN NOT NULL DEFAULT true,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_blog_sort ON blog_posts(sort_order);
CREATE INDEX IF NOT EXISTS idx_blog_slug ON blog_posts(slug);

ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read published blog" ON blog_posts;
DROP POLICY IF EXISTS "Authenticated read all blog" ON blog_posts;
DROP POLICY IF EXISTS "Authenticated insert blog" ON blog_posts;
DROP POLICY IF EXISTS "Authenticated update blog" ON blog_posts;
DROP POLICY IF EXISTS "Authenticated delete blog" ON blog_posts;

-- Anonymous visitors only see published posts…
CREATE POLICY "Public read published blog"
  ON blog_posts FOR SELECT USING (published = true);
-- …while authenticated admins can read drafts too (SELECT policies are OR'd).
CREATE POLICY "Authenticated read all blog"
  ON blog_posts FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated insert blog"
  ON blog_posts FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated update blog"
  ON blog_posts FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated delete blog"
  ON blog_posts FOR DELETE USING (auth.role() = 'authenticated');
