-- Run this script in the Supabase SQL Editor to create the necessary tables

-- Create Stores table
CREATE TABLE stores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  n TEXT NOT NULL,
  name TEXT NOT NULL,
  area TEXT NOT NULL,
  addr TEXT NOT NULL,
  hours TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  phone TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Offers table
CREATE TABLE offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  cat TEXT NOT NULL,
  offer TEXT NOT NULL,
  note TEXT,
  off TEXT,
  off_num INTEGER,
  price_num INTEGER,
  available BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Set up Row Level Security (RLS)
-- We want anyone to be able to read (SELECT) the data,
-- but only authenticated users (Admins) can modify (INSERT/UPDATE/DELETE) it.

-- Enable RLS
ALTER TABLE stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE offers ENABLE ROW LEVEL SECURITY;

-- Create Policies for Stores
CREATE POLICY "Enable read access for all users on stores" ON stores FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only on stores" ON stores FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update for authenticated users only on stores" ON stores FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Enable delete for authenticated users only on stores" ON stores FOR DELETE USING (auth.role() = 'authenticated');

-- Create Policies for Offers
CREATE POLICY "Enable read access for all users on offers" ON offers FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only on offers" ON offers FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update for authenticated users only on offers" ON offers FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Enable delete for authenticated users only on offers" ON offers FOR DELETE USING (auth.role() = 'authenticated');
